<a href="https://colab.research.google.com/github/ulises1229/ComputacionII-2021-2/blob/main/code/Comp_II_Sistemas_de_ecuaciones_lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computación II - Resolución de sistemas de ecuaciones lineales
+ Autor: Ulises  Olivares
+ Email: uolivares@unam.mx
+ Fecha: 17 febrero de 2021


## 0. *Numpy - Repaso*

Demostrar el uso de arreglos unidimensionales y bi-dimensionales utilizando numpy.


In [ ]:
# importar librería de numpy 
import numpy as np

# Se Crea un arreglo bi-dimensional
a = np.array([[1.0,2,3], 
              [4,5,6]], 
             dtype = np.float16)
# Imprimir matriz
print(a)

# IMPRIMIR ELEMENTOS
print("Dimensiones: " + str(a.ndim))
print("Forma: " + str(a.shape))
print("Tipo de datos: " + str(a.dtype))

[[1. 2. 3.]
 [4. 5. 6.]]
Dimensiones: 2
Forma: (2, 3)
Tipo de datos: float16


In [ ]:
# Creación de arreglos
# Arreglo de 1s
ones = np.ones((3,5), dtype=np.float32)
# Arreglo de 0s
zeros = np.zeros((5,5), dtype=np.float32)

#Impresión de matrices
print(ones)
print(zeros)

print("Matriz 1s tiene: " + str(len(ones)) + " filas y " + str(len(ones[0])) + " columnas")

# Acceso a la matriz usando índices
filas = len(ones)
columnas = len(ones[0])

print("Impresión utilizando índices")
for i in range(filas):
  for j in range(columnas):
    print(ones[i][j], end= " ")
  print(" ")

print("Impresión utilizando elementos")
# Acceso usando elementos
for i in ones:
  for j in i:
    print(j , end =" ")
  print(" ")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz 1s tiene: 3 filas y 5 columnas
Impresión utilizando índices
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
Impresión utilizando elementos
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  


In [ ]:
# Generación de un vector a través del uso de rangos
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# Concatenando arreglos o matrices
A = np.ones((3,3), dtype = np.float32)
B = np.zeros((3,3), dtype = np.float32)

# concatenar matrices
np.concatenate([A,B], axis = 1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
# Uso de astype para hacer un cast de tipos de datos
A = np.zeros((5,4), dtype = np.float32)
print(len(A[0]))

for i in range(len(A)):
  for j in range(len(A[0])):
    A[i][j] = np.pi
print(A)

print(A.astype(np.int16))

4
[[3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
# Uso de np.zeros_like y np.ones_like
A = np.ones((4,4))
print(A)
# zeros_like genera un arreglo de las 
# mismas dimensiones que el original 
B = np.zeros_like(A)
print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Generación de arreglos aleatorios
A = np.random.random((5, 5))
print(A)
# Generación de números enteros del 0 al n-1 
n = 10
B= np.random.randint(10, size = (7,7))
print(B)

[[0.71287072 0.29881262 0.08151383 0.53770453 0.72312097]
 [0.21578967 0.01990806 0.68173396 0.45855876 0.24962121]
 [0.93722388 0.40639213 0.70056761 0.41524328 0.8542108 ]
 [0.23657172 0.73113335 0.54375632 0.84581873 0.82910977]
 [0.08567112 0.31301573 0.31308052 0.51707265 0.21045252]]
[[5 1 9 8 0 3 4]
 [1 5 9 7 5 1 9]
 [1 1 1 5 0 7 5]
 [0 9 8 8 4 1 9]
 [3 5 4 1 0 2 9]
 [1 7 2 2 9 5 5]
 [4 7 8 8 4 2 6]]


In [ ]:
# Transformaciones de arreglos
A = np.array([1,2,3,4,5,6])
print(A)

# Transformar a 3 filas, 2 columnas
A = A.reshape(3, 2)
print(A)

# Se utiliza -1 para determinar cols
A = A.reshape(2, -1)
print(A)

# Transormar a un arreglo lineal
A = A.ravel()
print(A)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# Transpuesta de una matriz
A = np.arange(25).reshape(5,5)
print("Matriz Original: \n" + str(A))
# Imprimir matriz transpuesta
print("Matriz Transpuesta: \n" + str(A.T))
# Imprimir matriz 
print("Matriz Transpuesta: \n" + str(A.transpose((1,0))))



Matriz Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [ ]:
# Operadores Matemáticos
A = np.arange(100).reshape(10,10)
print("Primer Matriz: \n" + str(A))

B = np.arange(100, 200).reshape(10, 10)
print("Segunda Matriz: \n" + str(B))

# Calcular la suma de ambas matrices
print("Suma: "  + str(A + B))

# Calcular la resta de ambas matrices
print("resta: "  + str(B - A))

# Calcular la multiplicación de ambas matrices
print("multiplicación: "  + str(A * B))

Primer Matriz: 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Segunda Matriz: 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]
Suma: [[100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 1

In [ ]:
# Operadores lógicos
A = np.random.random((5,5))
print("Matriz Original: \n" + str(A))

# Operador lógico
print("Operador lógico a >5 \n" + str(A > 0.5))

Matriz Original: 
[[0.50745451 0.85742292 0.03131221 0.0220632  0.93748903]
 [0.79858488 0.02277429 0.98031463 0.09460174 0.03646411]
 [0.11670299 0.86145845 0.07489648 0.57176339 0.35089049]
 [0.97164412 0.18996996 0.58559677 0.62125253 0.72437122]
 [0.04110709 0.70706612 0.33786884 0.32971782 0.38878959]]
Operador lógico a >5 
[[ True  True False False  True]
 [ True False  True False False]
 [False  True False  True False]
 [ True False  True  True  True]
 [False  True False False False]]


In [ ]:
# Operaciones in-situ 
A = np.random.randint(10, size= (5,5))
print("Matriz A Original: \n" + str(A))

B = A = np.random.randint(10, size= (5,5))
print("Matriz B Original: \n" + str(B))

# Operación in-situ
A += B
print("Matriz A Modificada: \n" + str(A))

Matriz A Original: 
[[2 8 0 7 5]
 [9 2 9 4 3]
 [5 2 5 7 0]
 [3 1 4 8 3]
 [8 4 1 9 2]]
Matriz B Original: 
[[3 7 2 8 6]
 [7 1 4 4 4]
 [4 4 0 9 5]
 [5 1 6 3 9]
 [5 4 9 7 9]]
Matriz A Modificada: 
[[ 6 14  4 16 12]
 [14  2  8  8  8]
 [ 8  8  0 18 10]
 [10  2 12  6 18]
 [10  8 18 14 18]]


In [ ]:
# Funciones universales
A = np.random.randint(10, 100, size= (5,5))
print("Matriz A Original: \n" + str(A))

# Calcular Raiz cuadrada
print("Raiz Cuadrada: \n" + str(np.sqrt(A)))

# Calcular raiz a elemento de la matriz
print(np.sqrt(A[0][0]))


Matriz A Original: 
[[84 16 65 95 56]
 [34 51 64 17 48]
 [61 77 68 54 39]
 [26 84 34 48 44]
 [90 57 87 15 66]]
Raiz Cuadrada: 
[[9.16515139 4.         8.06225775 9.74679434 7.48331477]
 [5.83095189 7.14142843 8.         4.12310563 6.92820323]
 [7.81024968 8.77496439 8.24621125 7.34846923 6.244998  ]
 [5.09901951 9.16515139 5.83095189 6.92820323 6.63324958]
 [9.48683298 7.54983444 9.32737905 3.87298335 8.1240384 ]]
9.16515138991168


#### Inversa de una matriz


In [ ]:
# Inversa de una matriz
import numpy as np

# Inicializar una matriz 
A = np.random.randint(10, size= (5,5))
print("Matriz A Original: \n" + str(A))

# Calcular matriz inversa
B = np.linalg.inv(A)
print("Matriz Inversa A^-1: \n" + str(B))

Matriz A Original: 
[[6 0 2 9 8]
 [9 6 8 5 9]
 [1 3 6 8 5]
 [6 8 3 5 0]
 [7 9 6 8 7]]
Matriz Inversa A^-1: 
[[ 7.69230769e-02  1.12452570e-01 -6.33839255e-02  1.50051742e-01
  -1.87219731e-01]
 [-7.69230769e-02 -9.89996551e-02 -7.22662987e-02 -7.38185581e-02
   2.66816143e-01]
 [-7.69230769e-02  1.65574336e-01  1.76612625e-01  9.21007244e-02
  -2.51121076e-01]
 [ 7.69230769e-02 -7.58882373e-02  8.57192135e-02  8.27871680e-02
  -5.15695067e-02]
 [ 1.56250774e-17 -4.03587444e-02 -9.30493274e-02 -2.28699552e-01
   2.61210762e-01]]


***
Termina repaso de Numpy 
***

## 1. Eliminación Gaussiana

In [3]:
import numpy as np
import sympy

class GaussJordan:
    
    # Constructor
    #def init(self, filas, cols, M):
        #self.f = filas
        #self.c = cols
        #self.M = M

    """
        Método para intercambiar dos filas de la matriz M
        Entradas: indices de la primer y segunda fila 
        Salidas: Matriz M modificada
    """
    def intercambiarFilas(self, index1, index2, M):
        #print("A intercambiar", index1, " por ", index2)
        #print("Antes \n", M)
        for i in range(len(M[0])): # itera sobre el número de columnas
            tmp = M[index2][i]
            M[index2][i] = M[index1][i]
            M[index1][i] = tmp
        #print("Después:\n", M)
        return M

    
    def multiplicarFila(self, k, fila, colInicial, M):
        for i in range (colInicial, len(M[0])):
            M[fila][i] = k * M[fila][i]
        return M

    """
        Método empleado para realizar la eliminación resta dos filas
        Entradas: indices de  filas 1 y 2, columna inicial y Matriz
        Salida: Matriz M modficada
    """
    def restarFilas(self, f1, f2, colInicial, M):
        for i in range(colInicial, len(M[0])):
            M[f1][i] =  M[f2][i] - M[f1][i]
        return M 


    """
        Método para buscar un elemento pivote, se implementa pivoteo parcial
        Entradas: filas, columna actual y matriz
        Salidas: Matriz modificada
    """
    def buscarPivote(self, filas, col, M):
        indiceFila = -1
        maxNum = np.inf *-1
        for i in range(col+1, filas):
            if(M[i][col] > maxNum and M[i][col] != 0):
                indiceFila = i
                maxNum = M[i][col]
        return indiceFila

    #def calcularInversa(self, MAug, f, c):
        # self.GaussJordan()

    """
        Método para efectuar la eliminación Gaussiana
        Entradas: Número de filas y columnas, Matriz
        Salida: Matriz modificada
    """
    def eliminicacionGaussiana(self, f, c, M):
        # Definición de variables
        indicePiv = -1
        
        for i in range(f):
            pivote = M[i][i]
            if pivote == 0:
                indicePiv = self.buscarPivote(f, i, M) # Se implementa pivoteo parcial
                #TODO: Implementar pivoteo completo
                if indicePiv == -1:
                    print("El sistema no tiene solución")
                    exit(0)
                else:
                    M = self.intercambiarFilas(indicePiv, i, M)
                    pivote = M[i][i]
            
            for j in range(i+1, f): # Realizar la eliminación de los elementos debajo del pivote
                if M[j][i] != 0:
                    k = pivote / M[j][i]    # Multiplicador para la eliminación
                    M = self.multiplicarFila(k, j, i, M)
                    M = self.restarFilas(j, i, i, M)
        print("Matriz resultante: \n", M)

"""
    Método para calcular la inversa de una matriz M
    Entradas: Filas, columnas y Matriz original
    Salida: Matriz inversa
"""
def calculateInverse(f, c, M):
    # Definición de matriz identidad
    I = np.identity(f)
    print("Identidad: \n", I)

    MAug = np.concatenate([M,I], axis=1)
    print("Matriz aumentada: \n", MAug)
    # Generar matriz aumentada

def main():

    # Definición de número de filas y columnas
    f = 3
    c = f+1 # +1 se debe a la columna de resultados
    
    # Inicializar una matriz de 
    M = np.random.randint(10, size = (f,c))

    print("matrix aleatoria:\n", M)
    
    # Creación de un objeto
    objG = GaussJordan()
    print("Realizando eliminación Gaussiana...")
    objG.eliminicacionGaussiana(f, c, M) 





if __name__ == "__main__":
    main()

matrix aleatoria:
 [[9 0 7 6]
 [7 5 5 9]
 [9 4 5 1]]
Realizando eliminación Gaussiana...
Matriz resultante: 
 [[  9   0   7   6]
 [  0  -6   1  -5]
 [  0   0  -2 -12]]


## 2. El método gráfico (2D y 3D)

inf
-18446744073709551616
4294967296
